server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://svc.sel4.cloudtype.app:32393/ScheduleMgt?characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 1234

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  type-aliases-package: com.choi.PublicScheduleManage.Mapper
  configuration:
    map-underscore-to-camel-case: true

